# Generated by Django 3.1.2 on 2023-10-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_cidade_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
