# Generated by Django 3.1.2 on 2023-10-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
