# Generated by Django 3.1.2 on 2023-10-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_auto_20231011_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
    ]
