version: '3.5'

services:

  app:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/code
    entrypoint: ['sh', 'run-django.sh']
    depends_on:
      - bd

  proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx:/etc/nginx/conf.d/
      - ./log/nginx:/var/log/nginx
      - ./static:/var/www/static
      - ./media:/var/www/media
    depends_on:
      - app
    networks:
      - web

  bd:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sidia
    ports:
      - "5434:5432"
    volumes:
      - sidia-data-prod:/var/lib/postgresql/data


volumes:
  sidia-data-prod: